apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/erikdhoward1021/ml-inference-platform.git'
    targetRevision: HEAD
    path: k8s/overlays/dev   # your kustomize overlay
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ml-platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
